### ISSUE TITLE
Not working on Mobile browsers

### ISSUE THREAD

**Issue by yarnball** [btomashvili/react-redux-firebase-boilerplate#13]
Hi,

I've tested on both Chrome & Safari- the page loads, but "login" doesn't work. It does not direct to a new page after a password is entered. It also doesn't give error message when the incorrect password is entered.

**Comment by mrienstra** [comment]
Huh, oddly cannot reproduce in iOS Simulator, but seeing the same issue from my phone.

iPhone 5, iOS 9.3.5: login broken as described above

`[Error] Warning: [history] Unable to save state; sessionStorage is not available in Safari private mode`

(saw this error despite not being in private mode)

iOS Simulator, iPhone 5, iOS 9.3: login works fine

iOS Simulator, iPhone 5, iOS 10.0: login works fine

Hmm, may be related to `ReactTraining/react-router` using `ReactTraining/history` 3.0 (rather than 4.5)...

https://github.com/ReactTraining/history/issues/401

https://github.com/ReactTraining/react-router/issues/4365
