### ISSUE TITLE
Just FYI this seems to be no longer working.

### ISSUE THREAD

**Issue by timmeade** [btomashvili/react-redux-firebase-boilerplate#27]
Getting provider not supported in console from firebase.js line 29.

Clean install simple 
changed to our credentials
yarn: yarn run dev

**Comment by timmeade** [comment]
Interesting the reduxSagas branch works.   More what i was looking for....

**Comment by kevnsn** [comment]
I can confirm that this isn't working on a clean install, it's likely due to [this recent commit](https://github.com/btomashvili/react-redux-firebase-boilerplate/commit/2ef05be51009a872494415089fe9e9f228f85871).
(dispatching fetchUser with no provider)

Reverting to [this earlier commit](https://github.com/btomashvili/react-redux-firebase-boilerplate/commit/7fd6056a01978a63c458a85cd47cb2148420cd2c) also works fine!

**Comment by NikonMcFly** [comment]
This still isnt working.  Given action "FETCH_FIREBASE_USER", reducer "currentUser" returned undefined
